spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/springbootlevel1user
    username: magicuser
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource

  jpa:
    open-in-view: false
    show-sql: true
    hibernate.ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

  data:
    web:
      pageable:
        one-indexed-parameters: true